package thelm.textevents;

import java.io.File;
import java.util.Arrays;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.lwjgl.input.Keyboard;

import net.minecraft.client.Minecraft;
import net.minecraft.client.settings.KeyBinding;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(
		modid = TextEvents.MOD_ID,
		name = TextEvents.NAME,
		version = TextEvents.VERSION,
		clientSideOnly = true
		)
public class TextEvents {

	public static final String MOD_ID = "textevents";
	public static final String NAME = "TextEvents";
	public static final String VERSION = "1.12.2-1.0.0.0";
	public static final Logger LOGGER = LogManager.getLogger(NAME);
	static ModMetadata metadata;

	@EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.modId = MOD_ID;
		metadata.version = VERSION;
		metadata.name = NAME;
		metadata.credits="Author: TheLMiffy1111";
		metadata.authorList.addAll(Arrays.<String>asList("TheLMiffy1111"));
		metadata.description = "Coremod that adds events for certain rendered text.";
	}
}
