package thelm.textevents;

import java.util.Arrays;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import io.netty.channel.ChannelPipeline;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiMultiplayer;
import net.minecraft.client.network.NetHandlerPlayClient;
import net.minecraft.network.NetworkManager;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.network.FMLNetworkEvent.ClientConnectedToServerEvent;

@Mod(
		modid = TextEvents.MOD_ID,
		name = TextEvents.NAME,
		version = TextEvents.VERSION,
		clientSideOnly = true
		)
public class TextEvents {

	public static final String MOD_ID = "textevents";
	public static final String NAME = "TextEvents";
	public static final String VERSION = "1.12.2-2.0.0.0";
	public static final Logger LOGGER = LogManager.getLogger(NAME);
	static ModMetadata metadata;

	@EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(this);
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.modId = MOD_ID;
		metadata.version = VERSION;
		metadata.name = NAME;
		metadata.credits="Author: TheLMiffy1111";
		metadata.authorList.addAll(Arrays.<String>asList("TheLMiffy1111"));
		metadata.description = "Coremod that adds events for certain rendered text.";
	}
}
